// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID        int64
	Name      pgtype.Text
	Email     pgtype.Text
	CreatedAt pgtype.Timestamptz
}
