GET http://localhost:8080/v1/api/health

### 测试Movie项目 POST0

POST  http://localhost:8080/v1/api/createMovie
Content-Type:  application/json

{
    "id" : 0,
    "name" : "looksaw",
    "email" : "2814031084@qq.com"
}

### POST1
POST  http://localhost:8080/v1/api/createMovie
Content-Type:  application/json

{
    "id" : 1,
    "name" : "looksaw2",
    "email" : "2814031086@qq.com"
}


### GET
GET http://localhost:8080/v1/api/showMovie/1

### GET Movie All
GET http://localhost:8080/v1/api/showMovie/